INSERT INTO `Stores` (`branch_name`,`ingredient_name`,`available_quantity`)
VALUES
  ("Branch 1","Ingredient A",45),
  ("Branch 1","Ingredient B",83),
  ("Branch 1","Ingredient C",46),
  ("Branch 1","Ingredient D",28),
  ("Branch 1","Ingredient E",14),
  ("Branch 1","Ingredient F",74),
  ("Branch 1","Ingredient G",90),
  ("Branch 2","Ingredient A",83),
  ("Branch 2","Ingredient B",93),
  ("Branch 2","Ingredient C",53),
  ("Branch 2","Ingredient D",53),
  ("Branch 2","Ingredient E",55),
  ("Branch 2","Ingredient F",90),
  ("Branch 2","Ingredient G",77),
  ("Branch 3","Ingredient A",31),
  ("Branch 3","Ingredient J",7),
  ("Branch 3","Ingredient K",66),
  ("Branch 3","Ingredient L",83),
  ("Branch 3","Ingredient M",15),
  ("Branch 3","Ingredient N",74);
