INSERT INTO Stores (branch_name, ingredient_name, available_quantity) 
VALUES 
    ('Main Branch', 'Tomato', 100),
    ('Main Branch', 'Lettuce', 150),
    ('Main Branch', 'Onion', 120),
    ('Downtown Branch', 'Cucumber', 130),
    ('Downtown Branch', 'Carrot', 140),
    ('Downtown Branch', 'Spinach', 110),
    ('City Center Branch', 'Bell Pepper', 90),
    ('City Center Branch', 'Mushroom', 100),
    ('City Center Branch', 'Broccoli', 120),
    ('Westside Branch', 'Cauliflower', 100),
    ('Westside Branch', 'Potato', 150),
    ('Westside Branch', 'Sweet Potato', 100),
    ('Southside Branch', 'Zucchini', 110),
    ('Southside Branch', 'Eggplant', 120),
    ('Southside Branch', 'Green Beans', 130),
    ('Uptown Branch', 'Celery', 140),
    ('Uptown Branch', 'Kale', 100),
    ('Uptown Branch', 'Radish', 120),
    ('Midtown Branch', 'Arugula', 100),
    ('Midtown Branch', 'Cabbage', 110),
    ('Northside Branch', 'Tomato', 90),
    ('Northside Branch', 'Lettuce', 100),
    ('Northside Branch', 'Onion', 120),
    ('East End Branch', 'Cucumber', 110),
    ('East End Branch', 'Carrot', 100),
    ('East End Branch', 'Spinach', 110),
    ('Central Branch', 'Bell Pepper', 90),
    ('Central Branch', 'Mushroom', 100),
    ('Central Branch', 'Broccoli', 120),
    ('Oceanfront Branch', 'Cauliflower', 100),
    ('Oceanfront Branch', 'Potato', 150),
    ('Oceanfront Branch', 'Sweet Potato', 110),
    ('Hilltop Branch', 'Zucchini', 90),
    ('Hilltop Branch', 'Eggplant', 100),
    ('Hilltop Branch', 'Green Beans', 130),
    ('Riverside Branch', 'Celery', 120),
    ('Riverside Branch', 'Kale', 110),
    ('Riverside Branch', 'Radish', 100),
    ('Parkside Branch', 'Arugula', 90),
    ('Parkside Branch', 'Cabbage', 120),
    ('Harbor Branch', 'Tomato', 90),
    ('Harbor Branch', 'Lettuce', 100),
    ('Harbor Branch', 'Onion', 120),
    ('Mountain View Branch', 'Cucumber', 110),
    ('Mountain View Branch', 'Carrot', 100),
    ('Mountain View Branch', 'Spinach', 110),
    ('Lakefront Branch', 'Bell Pepper', 90),
    ('Lakefront Branch', 'Mushroom', 100),
    ('Lakefront Branch', 'Broccoli', 120),
    ('Sunset Branch', 'Cauliflower', 100),
    ('Sunset Branch', 'Potato', 150),
    ('Sunset Branch', 'Sweet Potato', 110),
    ('Rainbow Branch', 'Zucchini', 90),
    ('Rainbow Branch', 'Eggplant', 100),
    ('Rainbow Branch', 'Green Beans', 130),
    ('Valley Branch', 'Celery', 120),
    ('Valley Branch', 'Kale', 110),
    ('Valley Branch', 'Radish', 100),
    ('Greenfield Branch', 'Arugula', 90),
    ('Greenfield Branch', 'Cabbage', 120);