ALTER TABLE
    reserved ADD CONSTRAINT FOREIGN KEY(branch_name) REFERENCES branch(branch_name) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE
    reserved ADD CONSTRAINT FOREIGN KEY(order_id) REFERENCES Orders(order_id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE
    reserved ADD CONSTRAINT FOREIGN KEY(table_no) REFERENCES r_tables(table_no) ON UPDATE CASCADE ON DELETE CASCADE;