INSERT INTO Reserved (order_id, table_no, branch_name)
VALUES
    (1, 1, 'Main Branch'),
    (2, 2, 'Main Branch'),
    (3, 1, 'Downtown Branch'),
    (4, 2, 'Downtown Branch'),
    (5, 1, 'City Center Branch'),
    (6, 2, 'City Center Branch'),
    (7, 1, 'Westside Branch'),
    (8, 2, 'Westside Branch'),
    (9, 1, 'Southside Branch'),
    (10, 2, 'Southside Branch'),
    (11, 1, 'Uptown Branch'),
    (12, 2, 'Uptown Branch'),
    (13, 1, 'Midtown Branch'),
    (14, 2, 'Midtown Branch'),
    (15, 1, 'Northside Branch'),
    (16, 2, 'Northside Branch'),
    (17, 1, 'East End Branch'),
    (18, 2, 'East End Branch'),
    (19, 1, 'Central Branch'),
    (20, 2, 'Central Branch');