ALTER TABLE Shipment
	ADD CONSTRAINT FOREIGN KEY (branch_name) REFERENCES Branch(branch_name)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
;

ALTER TABLE Shipment
	ADD CONSTRAINT FOREIGN KEY (supplier_name) REFERENCES Supplier(supplier_name)
    ON UPDATE CASCADE
    ON DELETE CASCADE
;