INSERT INTO Shipment (shipment_id, status, supplier_name, branch_name) 
VALUES 
    (1, TRUE, 'supplier1', 'Main Branch'), 
    (2, FALSE, 'supplier2', 'Main Branch'), 
    (3, TRUE, 'supplier3', 'Main Branch'), 
    (4, TRUE, 'supplier4', 'Main Branch'), 
    (5, FALSE, 'supplier1', 'Downtown Branch'), 
    (6, TRUE, 'supplier1', 'City Center Branch'), 
    (7, TRUE, 'supplier1', 'Westside Branch'), 
    (8, FALSE, 'supplier2', 'Downtown Branch'), 
    (9, TRUE, 'supplier2', 'City Center Branch'), 
    (10, TRUE, 'supplier2', 'Westside Branch'), 
    (11, FALSE, 'supplier2', 'Southside Branch'), 
    (12, TRUE, 'supplier3', 'City Center Branch'), 
    (13, TRUE, 'supplier3', 'Uptown Branch'), 
    (14, FALSE, 'supplier3', 'Harbor Branch'), 
    (15, TRUE, 'supplier3', 'Valley Branch'), 
    (16, TRUE, 'supplier4', 'Heliopolis'), 
    (17, FALSE, 'supplier4', 'Midtown Branch'), 
    (18, TRUE, 'supplier4', 'Riverside Branch'), 
    (19, TRUE, 'supplier4', 'Central Branch'), 
    (20, FALSE, 'supplier4', 'East End Branch');
