INSERT INTO Shipment   (shipment_id, status, supplier_name, branch_name) VALUES
  (1,  TRUE,  "supplier1", "Main Branch"),
  (2,  FALSE, "supplier2", "Downtown Branch"),
  (3,  TRUE,  "supplier3", "City Center Branch"),
  (4,  TRUE,  "supplier4", "Westside Branch"),
  (5,  FALSE, "supplier5", "Southside Branch"),
  (6,  FALSE, "supplier6", "Uptown Branch"),
  (7,  TRUE,  "supplier7", "Midtown Branch"),
  (8,  TRUE,  "supplier8", "Northside Branch"),
  (9,  TRUE,  "supplier9", "East End Branch"),
  (10, FALSE, "supplier10", "Central Branch"),
  (11, TRUE,  "supplier11", "Oceanfront Branch"),
  (12, TRUE,  "supplier12", "Hilltop Branch"),
  (13, FALSE, "supplier13", "Riverside Branch"),
  (14, FALSE, "supplier14", "Parkside Branch"),
  (15, TRUE,  "supplier15", "Harbor Branch"),
  (16, TRUE,  "supplier16", "Mountain View Branch"),
  (17, TRUE,  "supplier17", "Lakefront Branch"),
  (18, FALSE, "supplier18", "Sunset Branch"),
  (19, TRUE,  "supplier19", "Rainbow Branch"),
  (20, TRUE,  "supplier20", "Valley Branch"),
  (21, FALSE, "supplier1", "Greenfield Branch"),
  (22, FALSE, "supplier2", "Main Branch"),
  (23, TRUE,  "supplier3", "Downtown Branch"),
  (24, TRUE,  "supplier4", "City Center Branch"),
  (25, TRUE,  "supplier5", "Westside Branch"),
  (26, FALSE, "supplier6", "Southside Branch"),
  (27, TRUE,  "supplier7", "Uptown Branch"),
  (28, TRUE,  "supplier8", "Midtown Branch"),
  (29, FALSE, "supplier9", "Northside Branch"),
  (30, FALSE, "supplier10", "East End Branch"),
  (31, TRUE,  "supplier11", "Central Branch"),
  (32, TRUE,  "supplier12", "Oceanfront Branch"),
  (33, TRUE,  "supplier13", "Hilltop Branch"),
  (34, FALSE, "supplier14", "Riverside Branch"),
  (35, TRUE,  "supplier15", "Parkside Branch"),
  (36, TRUE,  "supplier16", "Harbor Branch"),
  (37, FALSE, "supplier17", "Mountain View Branch"),
  (38, FALSE, "supplier18", "Lakefront Branch"),
  (39, TRUE,  "supplier19", "Sunset Branch"),
  (40, TRUE,  "supplier20", "Rainbow Branch"),
  (41, TRUE,  "supplier1", "Valley Branch"),
  (42, FALSE, "supplier2", "Greenfield Branch"),
  (43, TRUE,  "supplier3", "Main Branch"),
  (44, TRUE,  "supplier4", "Downtown Branch"),
  (45, FALSE, "supplier5", "City Center Branch"),
  (46, FALSE, "supplier6", "Westside Branch"),
  (47, TRUE,  "supplier7", "Southside Branch"),
  (48, TRUE,  "supplier8", "Uptown Branch"),
  (49, TRUE,  "supplier9", "Midtown Branch"),
  (50, FALSE, "supplier10", "Northside Branch");
