ALTER TABLE Manager
	ADD CONSTRAINT FOREIGN KEY (employee_ssn) REFERENCES Employee(employee_ssn)
    ON UPDATE CASCADE
    ON DELETE CASCADE
;
ALTER TABLE Manager
	ADD CONSTRAINT FOREIGN KEY (branch_name) REFERENCES Branch(branch_name)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
;