 ALTER TABLE
    Owns ADD CONSTRAINT FOREIGN KEY(tool_name) REFERENCES Tool(tool_name) ON UPDATE CASCADE ON DELETE CASCADE;
 ALTER TABLE
    Owns ADD CONSTRAINT FOREIGN KEY(branch_name) REFERENCES Branch(branch_name) ON UPDATE CASCADE ON DELETE CASCADE;