 ALTER TABLE
    owns ADD CONSTRAINT FOREIGN KEY(tool_name) REFERENCES Tool(tool_name) ON UPDATE CASCADE ON DELETE CASCADE;
 ALTER TABLE
    owns ADD CONSTRAINT FOREIGN KEY(branch_name) REFERENCES branch(branch_name) ON UPDATE CASCADE ON DELETE CASCADE;