INSERT INTO Owns (tool_name, branch_name, quantity) VALUES
    ('Stove', 'Main Branch', 5),
    ('Oven', 'Main Branch', 3),
    ('Microwave', 'Main Branch', 2),
    ('Refrigerator', 'Main Branch', 4),
    ('Dishwasher', 'Main Branch', 2),
    ('Knife', 'Main Branch', 20),
    ('Frying pan', 'Main Branch', 15),
    ('Cutting board', 'Main Branch', 10),
    ('Blender', 'Main Branch', 3),
    ('Toaster', 'Main Branch', 5),
    ('Coffee maker', 'Main Branch', 4),
    ('Grill', 'Main Branch', 2),
    ('Waffle maker', 'Main Branch', 2),
    ('Rice cooker', 'Main Branch', 3),
    ('Pressure cooker', 'Main Branch', 3),
    ('Juicer', 'Main Branch', 3),
    ('Ice cream maker', 'Main Branch', 2),
    ('Bread maker', 'Main Branch', 2),
    ('Electric kettle', 'Main Branch', 5),
    ('Stove', 'Downtown Branch', 4),
    ('Oven', 'Downtown Branch', 3),
    ('Microwave', 'Downtown Branch', 2),
    ('Refrigerator', 'Downtown Branch', 3),
    ('Dishwasher', 'Downtown Branch', 2),
    ('Knife', 'Downtown Branch', 15),
    ('Frying pan', 'Downtown Branch', 12),
    ('Cutting board', 'Downtown Branch', 8),
    ('Blender', 'Downtown Branch', 3),
    ('Toaster', 'Downtown Branch', 4)
;
