ALTER TABLE Made_with
	ADD CONSTRAINT FOREIGN KEY (tool_name) REFERENCES Tool(tool_name)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    ADD FOREIGN KEY (menu_item_id) REFERENCES Menu_item(menu_item_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
;